### ISSUE TITLE
exception trace from crawler running in periodic mode when interruted

### ISSUE THREAD

**Issue by sastryduri** [cloudviz/agentless-system-crawler#100]
^CProcess crawler-0:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
Traceback (most recent call last):
  File "crawler.py", line 427, in <module>
    self.run()
  File "/usr/local/lib/python2.7/multiprocessing/process.py", line 114, in run
        self._target(_self._args, *_self._kwargs)
  File "crawler.py", line 62, in crawler_worker
start_autonomous_crawler(args.numprocesses, args.logfile)
  File "crawler.py", line 112, in start_autonomous_crawler
    crawlutils.snapshot(**params)

A crawler instance was started with frequency 1. When this crawler was terminated with <crtl>-c
it throws an exception trace. It should exit more gracefully.

bash crawl.sh containers --features=os,cpu,interface,connection --frequency 1

File "/crawler/crawlutils.py", line 557, in snapshot
    time.sleep(0.1)
    time.sleep(time_to_sleep)
KeyboardInterrupt
KeyboardInterrupt
Process crawler-1:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/local/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(_self._args, *_self._kwargs)
  File "crawler.py", line 62, in crawler_worker
    crawlutils.snapshot(**params)
  File "/crawler/crawlutils.py", line 557, in snapshot
    time.sleep(time_to_sleep)
KeyboardInterrupt

**Comment by ricarkol** [comment]
fixed
