### ISSUE TITLE
crawler dies with an exception

### ISSUE THREAD

**Issue by sastryduri** [cloudviz/agentless-system-crawler#141]
## Description
Crawler died with following exception. It is possible that kafka server went down or otherwise unavailable. Crawler should log the failure but should continue without dying.

I notice that crawler is retrying `max_emit_retries` to emit and then raises exception which leads to its termination. My suggestion is that after `max_emit_retries` it should abort sending current message, and wait for next iteration, without dying. This approach helps in reducing maintenance associated with crawler restarts if there are intermittent network disruptions. 
```
```
## Log Output

```
Process crawler-1:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/local/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "crawler.py", line 61, in crawler_worker
    crawlutils.snapshot(**params)
  File "/crawler/crawlutils.py", line 324, in snapshot
    overwrite=overwrite
  File "/crawler/crawlutils.py", line 209, in snapshot_container
    ignore_exceptions=ignore_exceptions)
  File "/crawler/emitter.py", line 427, in __exit__
    self._publish(url)
  File "/crawler/emitter.py", line 403, in _publish
    self._publish_to_kafka(url, self.max_emit_retries)
  File "/crawler/emitter.py", line 373, in _publish_to_kafka
    raise e
EmitterEmitTimeout
Traceback (most recent call last):
  File "crawler.py", line 419, in <module>
    main()
  File "crawler.py", line 415, in main
    start_autonomous_crawler(args.numprocesses, args.logfile, params, options)
  File "crawler.py", line 116, in start_autonomous_crawler
    (pname, exitcode))
RuntimeError: crawler-1 terminated unexpectedly with errorcode 1
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/multiprocessing/queues.py", line 268, in _feed
    send(obj)
IOError: [Errno 32] Broken pipe

```

## Debugging Commands Output

**Output of `docker version`:**

```
docker version
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 22:00:36 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 22:00:36 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
docker info
Containers: 101
 Running: 100
 Paused: 0
 Stopped: 1
Images: 14
Server Version: 1.12.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 250
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host bridge overlay null
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 3.16.0-76-generic
Operating System: Ubuntu 14.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.67 GiB
Name: crawltest.sl.cloud9.ibm.com
ID: 2AWA:7F3N:RFHD:QEKR:SGYP:JZLZ:VVQU:ORT6:CYLU:FNUZ:VBP7:Y2W5
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: sastryduri
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

**Output of `python --version`:**

```
Python 2.7.6 (default, Jun 22 2015, 17:58:13)
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
```

**Output of `pip freeze`:**

```

```

**Comment by ricarkol** [comment]
fixed with #143
