### ISSUE TITLE
Temporary issue while moving to plugin model

### ISSUE THREAD

**Issue by sahilsuneja1** [cloudviz/agentless-system-crawler#156]
## Description

for features crawled by the plugin (e.g. 'os'), and hence not actually part of the legacy features list, remove them from the feature list passed to _snapshot_single_frame() in crawlutils.py. Otherwise error in crawler-0.log (although correct output still show up in csv):

2016-09-16 20:03:45,470 crawler-0  ERROR    'os'
Traceback (most recent call last):
  File "/root/agentless-system-crawler/crawler/crawlutils.py", line 66, in _snapshot_single_frame
    for (key, val) in crawler.funcdict[feature](feature_options):
KeyError: 'os'
## How to Reproduce

sudo python crawler/crawler.py --crawlmode OUTCONTAINER  --url file://output/test.csv  --features os,cpu  --logfile output/crawler.log
## Log Output

2016-09-16 20:03:45,470 crawler-0  ERROR    'os'
Traceback (most recent call last):
  File "/root/agentless-system-crawler/crawler/crawlutils.py", line 66, in _snapshot_single_frame
    for (key, val) in crawler.funcdict[feature](feature_options):
KeyError: 'os'
## Debugging Commands Output

**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Output of `python --version`:**

```
(paste your output here)
```

**Output of `pip freeze`:**

```
(paste your output here)
```

**Comment by sahilsuneja1** [comment]
@ricarkol , FYI, an action might not be needed right now
