### ISSUE TITLE
Feature: Support emitting to HTTPS URLs

### ISSUE THREAD

**Issue by niltonb** [cloudviz/agentless-system-crawler#249]
## Description
When using an HTTPS address with parameter `--url`  the crawler fails with the following exception:
```
Traceback (most recent call last):
  File "crawler.py", line 238, in <module>
    main()
  File "crawler.py", line 201, in main
    extra_metadata=args.extraMetadata)
  File "/crawler/emitters_manager.py", line 95, in __init__
    self.allocate_emitter(url)
  File "/crawler/emitters_manager.py", line 109, in allocate_emitter
    raise EmitterUnsupportedProtocol('Not supported: %s' % proto)
utils.crawler_exceptions.EmitterUnsupportedProtocol: Not supported: https
```

## How to Reproduce
Use an HTTPS URL with crawler invocation like 
```
CRAWLER --crawlmode OUTCONTAINER \
          --url https://localhost/frame\
          --features os,disk,process,connection,metric,package,file,config \
          --logfile output/crawler.log```

## Log Output
<!-- Include or upload the contents of the crawler-*.log files that show the issue -->

## Debugging Commands Output
<!-- Include the output of the following commands to help us debug your issue -->
**Output of `docker version`:**

```
(paste your output here)
```


**Output of `docker info`:**

```
(paste your output here)
```


**Output of `python --version`:**

```
Python 2.7.13
```


**Output of `pip freeze`:**

```
configobj==4.7.0
docker-py==1.10.6
docker-pycreds==0.2.1
ipaddress==1.0.18
kafka-python==1.3.1
kazoo==2.2.1
morph==0.1.2
netifaces==0.10.4
psutil==2.1.3
pykafka==1.1.0
python-dateutil==2.4.2
redis==2.10.5
requests==2.5.0
semantic-version==2.5.0
six==1.10.0
tabulate==0.7.7
virtualenv==15.1.0
websocket-client==0.40.0
Yapsy==1.11.223
root@c67d09386d01:/crawler# 
```

**Comment by nadgowdas** [comment]
@niltonb can you give us your services https endpoint, i can test it with ?

**Comment by nadgowdas** [comment]
@niltonb I've added a new https emitter plugin...and I was able to test it with my local https node.js server..
```
# python crawler.py --crawlmode OUTCONTAINER --url https://localhost:8000/frame --features os,disk,process,connection,metric,package,file,config --logfile /tmp/crawler.log
```

once you let me know your service's https endpoint, i will test it against it. 

NOTE:
======
I am using self-signed certificate during this test. Do you have any specific CA for your https endpoint ?
