### ISSUE TITLE
Docker version check failed

### ISSUE THREAD

**Issue by nadgowdas** [cloudviz/agentless-system-crawler#260]
## Description
Crawler docker version check fails for rc build versions of docker

## How to Reproduce
Install any rc build docker version and run crawler with it. 

## Log Output
```
Traceback (most recent call last):
 File "crawler.py", line 239, in <module>
   main()
 File "crawler.py", line 233, in main
   worker.run()
 File "/crawler/worker.py", line 83, in run
   self.iterate(time_to_sleep)
 File "/crawler/worker.py", line 46, in iterate
   for frame in self.crawler.crawl():
 File "/crawler/containers_crawler.py", line 85, in crawl
   host_namespace=self.host_namespace)
 File "/crawler/containers.py", line 83, in get_containers
   for _container in containers_list:
 File "/crawler/containers.py", line 26, in list_all_containers
   user_list=user_list):
 File "/crawler/dockercontainer.py", line 59, in get_docker_containers
   host_namespace=host_namespace)
 File "/crawler/dockercontainer.py", line 171, in __init__
   self.root_fs = get_docker_container_rootfs_path(self.long_id)
 File "/crawler/utils/dockerutils.py", line 359, in get_docker_container_rootfs_path
   rootfs_path = _get_container_rootfs_path_aufs(long_id, inspect)
 File "/crawler/utils/dockerutils.py", line 277, in _get_container_rootfs_path_aufs
   if VERSION_SPEC.match(semantic_version.Version(server_version)):
 File "/usr/local/lib/python2.7/site-packages/semantic_version/base.py", line 75, in __init__
   major, minor, patch, prerelease, build = self.parse(version_string, partial)
 File "/usr/local/lib/python2.7/site-packages/semantic_version/base.py", line 208, in parse
   raise ValueError("Invalid leading zero in minor: %r" % version_string)
ValueError: Invalid leading zero in minor: u'17.03.0-ce'
```

## Docker info
```
sudo docker info
Containers: 13
Running: 7
Paused: 0
Stopped: 6
Images: 7
Server Version: 17.03.0-ce
```

## Solution
Stefan mentioned, with semantic_version=2.2, it work. But we are using sematic_version 2.5.
Fixed this issue and add a new docker version in the travis tests

**Comment by nadgowdas** [comment]
Docker has decided to have monthly release cycle and follow YY.MM version format.
https://github.com/docker/docker/blob/master/CHANGELOG.md

We need long term fix for this
