### ISSUE TITLE
Crawler Image Build failed at ibm_db in requirements

### ISSUE THREAD

**Issue by yuji-watanabe-jp** [cloudviz/agentless-system-crawler#265]
## Description
failed to build crawler image

## How to Reproduce
docker build -t crawler .
The error below is produced. 

If the line https://github.com/cloudviz/agentless-system-crawler/blob/master/requirements.txt#L13 is removed, build is successful. 

## Log Output
```
Collecting ibm_db>=2.0.7 (from -r requirements.txt (line 13))
  Downloading ibm_db-2.0.7.tar.gz (553kB)
    Complete output from command python setup.py egg_info:
    Detected 64-bit Python
    Downloading https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/linuxx64_odbc_cli.tar.gz
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-2EZb51/ibm-db/setup.py", line 159, in <module>
        file_stream = BytesIO(request.urlopen(url).read())
      File "/usr/local/lib/python2.7/urllib2.py", line 154, in urlopen
        return opener.open(url, data, timeout)
      File "/usr/local/lib/python2.7/urllib2.py", line 429, in open
        response = self._open(req, data)
      File "/usr/local/lib/python2.7/urllib2.py", line 447, in _open
        '_open', req)
      File "/usr/local/lib/python2.7/urllib2.py", line 407, in _call_chain
        result = func(*args)
      File "/usr/local/lib/python2.7/urllib2.py", line 1241, in https_open
        context=self._context)
      File "/usr/local/lib/python2.7/urllib2.py", line 1198, in do_open
        raise URLError(err)
    urllib2.URLError: <urlopen error [Errno 110] Connection timed out>
```

**Comment by yuji-watanabe-jp** [comment]
@hitomitak

**Comment by hitomitak** [comment]
I already have removed this line and created PR ( #263 ). 
"Connection timed out" error means that pip cannot download tgz file. So I think the download server is down or your environment does not have connectivity to this URL.

**Comment by yuji-watanabe-jp** [comment]
@hitomitak thanks. 
@sahilsuneja1 pleaset take a look at PR #263 and process if it is ok. Thanks.

**Comment by sahilsuneja1** [comment]
@yuji-watanabe-jp I was waiting on other PRs before merging this one [ to avoid rebasing :) ]
But I'll go ahead merge it

**Comment by yuji-watanabe-jp** [comment]
@sahilsuneja1 thank you so much!
